name: Docker Image scan via cli
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Docker Image scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/sneha0302/docker-vulnerable-dvwa:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        run: |
         # sudo apt-get install wget apt-transport-https gnupg lsb-release
          #sudo wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          #echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          #sudo apt-get update
          #sudo apt-get install trivy
          #------------------------
         # wget https://github.com/aquasecurity/trivy/releases/download/v0.24.1/trivy_0.24.1_Linux-64bit.deb
         # sudo dpkg -i trivy_0.24.1_Linux-64bit.deb
          #------------
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.24.1
          trivy --version
          #trivy image -f json -o trivy-results.json --exit-code 1 --security-checks vuln  --download-db-only true  docker.io/sneha0302/docker-vulnerable-dvwa:${{ github.sha }}
          trivy image --format sarif --output trivy-results.sarif --exit-code 0  docker.io/sneha0302/docker-vulnerable-dvwa:${{ github.sha }}
          
     # - name: Upload Trivy scan results to GitHub Security tab
      #  uses: github/codeql-action/upload-sarif@v1
       # if: always() 
        #with:
         # sarif_file: 'trivy-results.sarif'
          
      - name: Archive Scan results
        uses: actions/upload-artifact@v2
        with:
          name: scan-report
          path: trivy-results.sarif         
